In [7]:
import pandas as pd

df = pd.read_csv('morningstar-industry_code.tsv', sep='\t', header=None, names=['Super Sector Name', 'Super Sector Code', 'Sector Name', 'Sector Code',
                                                                                'Group Name', 'Group Code', 'Industry Name', 'Industry Code'])

In [8]:
df

,Super Sector Name,Super Sector Code,Sector Name,Sector Code,Group Name,Group Code,Industry Name,Industry Code
0,Cyclical,1,Basic Materials,101,Agriculture,10110,Agricultural Inputs,10110010
1,Cyclical,1,Basic Materials,101,Building Materials,10120,Building Materials,10120010
2,Cyclical,1,Basic Materials,101,Chemicals,10130,Chemicals,10130010
3,Cyclical,1,Basic Materials,101,Chemicals,10130,Specialty Chemicals,10130020
4,Cyclical,1,Basic Materials,101,Forest Products,10140,Lumber & Wood Production,10140010
...,...,...,...,...,...,...,...,...
140,Sensitive,3,Technology,311,Hardware,31120,Electronics & Computer Distribution,31120050
141,Sensitive,3,Technology,311,Hardware,31120,Scientific & Technical Instruments,31120060
142,Sensitive,3,Technology,311,Semiconductors,31130,Semiconductor Equipment & Materials,31130010
143,Sensitive,3,Technology,311,Semiconductors,31130,Semiconductors,31130020
144,Sensitive,3,Technology,311,Semiconductors,31130,Solar,31130030